### ISSUE TITLE
How do you do Background Extraction for the Epic-Kitchens dataset?

### ISSUE THREAD

**Issue by selva604** [CVIR/CoMix#1]
Hello.
I'm trying to train CoMix for the trasfer task of D1-D2 from Epic-Kitchens dataset.
Could you tell me example code for the Epic-Kitchens on extract_bg_tmf.py.

**Comment by AadSah** [comment]
Hi @selva604 

Thanks for your interest. Background extraction for Epic-Kitchens requires some minor changes on reading the input file, as we now have `.pkl` instead of the `.csv` files.
I have pushed a file with the required changes. You can find it here: https://github.com/CVIR/CoMix/blob/main/background_extraction/extract_bg_tmf_epickitchens.py

Thanks

**Comment by selva604** [comment]
Thanks!
